/**
 * PDF Report HTML Template
 * High-fidelity template for DocRaptor/wkhtmltopdf rendering.
 * All data injected server-side; no client scripts.
 */

export interface ReportTemplateData {
  reportId: string
  version: number
  createdAt: string
  generatedBy: string
  pickupData?: {
    technicianName?: string
    pickupTime?: string
    gpsLat?: number
    gpsLng?: number
    location?: string
    vialIds?: string[]
    deviceId?: string
    pH?: number
    chlorine?: number
  }
  labResults?: {
    spcResult?: number
    spcUnit?: string
    spcReference?: string
    totalColiformResult?: number
    totalColiformUnit?: string
    totalColiformReference?: string
    testedAt?: string
    testedBy?: string
  }
  attachments?: Array<{ filename: string; fileType: string }>
  signatures?: Array<{
    signerName: string
    signerRole: string
    signedAt: string
    signatureImageUrl?: string
  }>
  auditTrail?: Array<{
    action: string
    performedBy?: string
    performedAt: string
    note?: string
  }>
}

function escapeHtml(s: string): string {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

export function renderReportHtml(data: ReportTemplateData): string {
  const d = data ?? {}
  const reportId = escapeHtml(String(d.reportId ?? '—'))
  const version = String(d.version ?? 1)
  const createdAt = escapeHtml(String(d.createdAt ?? '—'))
  const generatedBy = escapeHtml(String(d.generatedBy ?? '—'))

  const pickup = d.pickupData ?? {}
  const lab = d.labResults ?? {}
  const attachments = Array.isArray(d.attachments) ? d.attachments : []
  const signatures = Array.isArray(d.signatures) ? d.signatures : []
  const auditTrail = Array.isArray(d.auditTrail) ? d.auditTrail : []

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Water Test Report - ${reportId}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif; font-size: 12px; line-height: 1.5; color: #1a1a1a; }
    .container { max-width: 800px; margin: 0 auto; padding: 24px; }
    .header { border-bottom: 2px solid #006D64; padding-bottom: 16px; margin-bottom: 24px; }
    .header h1 { font-size: 24px; color: #006D64; padding-bottom: 4px; }
    .header .meta { font-size: 11px; color: #64748b; }
    .section { margin-bottom: 24px; }
    .section-title { font-size: 14px; font-weight: 600; color: #006D64; margin-bottom: 16px; margin-top: 0; padding-bottom: 4px; border-bottom: 1px solid #e2e8f0; }
    table { width: 100%; border-collapse: collapse; }
    th, td { padding: 8px 12px; text-align: left; border-bottom: 1px solid #e2e8f0; }
    th { font-weight: 600; color: #475569; }
    .signature-block { border: 1px solid #e2e8f0; padding: 16px; margin-top: 8px; }
    .signature-block img { max-height: 60px; max-width: 200px; }
    .audit-item { padding: 8px 0; border-bottom: 1px solid #f1f5f9; font-size: 11px; }
    .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 10px; color: #64748b; }
    @media print { .container { padding: 16px; } }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>AquaTrace Water Test Report</h1>
      <div class="meta">Report ID: ${reportId} · Version: ${version} · Created: ${createdAt} · Generated by: ${generatedBy}</div>
    </div>

    <div class="section">
      <h2 class="section-title">Pickup Data</h2>
      <table>
        <tr><th>Technician</th><td>${escapeHtml(String(pickup.technicianName ?? '—'))}</td></tr>
        <tr><th>Pickup Time</th><td>${escapeHtml(String(pickup.pickupTime ?? '—'))}</td></tr>
        <tr><th>GPS</th><td>${pickup.gpsLat != null && pickup.gpsLng != null ? `${pickup.gpsLat}, ${pickup.gpsLng}` : '—'}</td></tr>
        <tr><th>Location</th><td>${escapeHtml(String(pickup.location ?? '—'))}</td></tr>
        <tr><th>Vial IDs</th><td>${Array.isArray(pickup.vialIds) ? pickup.vialIds.join(', ') : '—'}</td></tr>
        <tr><th>Device ID</th><td>${escapeHtml(String(pickup.deviceId ?? '—'))}</td></tr>
        <tr><th>pH</th><td>${pickup.pH != null ? String(pickup.pH) : '—'}</td></tr>
        <tr><th>Chlorine</th><td>${pickup.chlorine != null ? String(pickup.chlorine) : '—'}</td></tr>
      </table>
    </div>

    <div class="section">
      <h2 class="section-title">Lab Results</h2>
      <table>
        <tr><th>SPC Result</th><td>${lab.spcResult != null ? String(lab.spcResult) : '—'} ${escapeHtml(String(lab.spcUnit ?? ''))}</td></tr>
        <tr><th>SPC Reference</th><td>${escapeHtml(String(lab.spcReference ?? '—'))}</td></tr>
        <tr><th>Total Coliform</th><td>${lab.totalColiformResult != null ? String(lab.totalColiformResult) : '—'} ${escapeHtml(String(lab.totalColiformUnit ?? ''))}</td></tr>
        <tr><th>Total Coliform Reference</th><td>${escapeHtml(String(lab.totalColiformReference ?? '—'))}</td></tr>
        <tr><th>Tested At</th><td>${escapeHtml(String(lab.testedAt ?? '—'))}</td></tr>
        <tr><th>Tested By</th><td>${escapeHtml(String(lab.testedBy ?? '—'))}</td></tr>
      </table>
    </div>

    ${attachments.length > 0 ? `
    <div class="section">
      <h2 class="section-title">Attachments</h2>
      <table>
        ${attachments.map((a) => `<tr><td>${escapeHtml(a.filename ?? '')}</td><td>${escapeHtml(a.fileType ?? '')}</td></tr>`).join('')}
      </table>
    </div>
    ` : ''}

    ${signatures.length > 0 ? `
    <div class="section">
      <h2 class="section-title">Signatures</h2>
      ${signatures.map((s) => `
      <div class="signature-block">
        ${s.signatureImageUrl ? `<img src="${escapeHtml(s.signatureImageUrl)}" alt="Signature" />` : ''}
        <div><strong>${escapeHtml(s.signerName ?? '')}</strong> · ${escapeHtml(s.signerRole ?? '')}</div>
        <div class="meta">Signed: ${escapeHtml(String(s.signedAt ?? '—'))}</div>
      </div>
      `).join('')}
    </div>
    ` : ''}

    ${auditTrail.length > 0 ? `
    <div class="section">
      <h2 class="section-title">Audit Trail</h2>
      ${auditTrail.map((e) => `
      <div class="audit-item">${escapeHtml(e.action ?? '')} · ${escapeHtml(String(e.performedAt ?? '—'))} · ${escapeHtml(String(e.performedBy ?? '—'))} · ${escapeHtml(String(e.note ?? ''))}</div>
      `).join('')}
    </div>
    ` : ''}

    <div class="footer">
      <p>Report ID: ${reportId} · Version ${version} · Generated ${createdAt}</p>
      <p>AquaTrace Water Sample Testing & Reporting Platform · Compliance records retained per regulatory requirements.</p>
    </div>
  </div>
</body>
</html>`
}
